version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - scnetwork

  redis:
    env_file:
      - .env
    image: redis:5.0.4-stretch
    volumes:
      - ./redis:/data
    networks:
      - scnetwork

  web:
    image: fuzzy-memory:latest
    build:
      context: .
      dockerfile: dockers/app/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/code
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    links:
      - redis
    networks:
      - scnetwork

  worker:
    image: fuzzy-memory:latest
    build:
      context: .
      dockerfile: dockers/app/Dockerfile
    env_file:
      - .env
    command: python manage.py rqworker default
    volumes:
      - ./app:/code
    depends_on:
      - db
      - redis
    links:
      - redis
    networks:
      - scnetwork

  frontend:
    image: fuzzy-memory-frontend:latest
    build:
      context: .
      dockerfile: dockers/frontend/Dockerfile
    volumes:
      - ./frontend/second-tetration:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - 8080:8080
    networks:
      - scnetwork

networks:
  scnetwork: {}
