version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    env_file:
      - .env
    image: redis:5.0.4-stretch
    volumes:
      - "./redis:/data"

  web:
    image: fuzzy-memory:latest
    build:
      context: .
      dockerfile: dockers/app/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/code
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    links:
      - redis

  worker:
    image: fuzzy-memory:latest
    build:
      context: .
      dockerfile: dockers/app/Dockerfile
    env_file:
      - .env
    command: python manage.py rqworker default
    volumes:
      - ./app:/code
    depends_on:
      - db
      - redis
    links:
      - redis
